version: 2.1
jobs:
  run_tests:
    docker: 
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Server
          command: |
            python -m gunicorn app:app --timeout 120
workflows:
  build_test:
    jobs:
      - run_tests
