version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python app.py
  test:
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python app.py

workflows:
  build:
    jobs:
      - build
